### 
GET http://localhost:5000/movies

###
Get http://localhost:5000/movies/tt10323676

###

GET http://localhost:5000/tvShows/tt1173427

###

GET http://localhost:5000/tvShows/54
###

GET http://localhost:5000/users/qtuGIkVmV8XWcXYD6OpTeYEqvqy2
 
###
 
GET http://localhost:5000/users/61fa72d57a80163b6d85615f

### 
POST http://localhost:5000/users
content-type: application/json

{
    "email" : "1@gmail.com",
    "watchList" : [],
    "favoritesList": [],
    "localId":"bo6NsSJ9ZuO9WkvDlpNAqcTDgHh1"
}

###

PATCH  http://localhost:5000/users/qtuGIkVmV8XWcXYD6OpTeYEqvqy2
content-type: application/json

{
    
    "watchList": ["spiderman", "suits"]
}

###
PATCH  http://localhost:5000/users/delete/qtuGIkVmV8XWcXYD6OpTeYEqvqy2
content-type: application/json
 
{
    
    "id":"tt14833702"
}